### ISSUE TITLE
WebRTC Connection Failed

### ISSUE THREAD

**Issue by drphero** [ai-dock/desktop#2]
The connection fails for WebRTC on both Vast and RunPod. VNC connects but is so laggy that it is unusable.

**Comment by robballantyne** [comment]
This is likely caused by poor connection.  You can try:

- Hosts in alternative locations 
- Use an external turn server

**Comment by drphero** [comment]
I'm not sure if that's the cause because using the runpod/kasm-docker:cuda11 image, which uses VNC, runs fairly well when deploying to the same machine.

**Comment by robballantyne** [comment]
Did you test the VNC (Kasm VNC fallback) for this image to compare against the alternative?

I have found much better performance of this image on Vast.ai Vs RunPod but I'd like to make it better on all platforms
