### ISSUE TITLE
XCB ERROR

### ISSUE THREAD

**Issue by hapnan** [ai-dock/desktop#5]
I just rented a server on vast.ai using the template provided and I didn't change anything in the template, and when I opened it there was an error like the one in the picture, what can I do?

![image](https://github.com/ai-dock/linux-desktop/assets/34102619/67c642d1-6294-4cf8-bc80-848dac8f6ff3)

**Comment by robballantyne** [comment]
No issue here. This log looks normal, albeit noisy
